Features/news-pages
kotkowo/kotkowo pull request #37
Opened 2023-09-22 07:24 UTC by RustySnek

2023-09-23 11:46 UTC, ravensiris requested changes

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo/announcement.ex
> +  defstruct [:title, :image, :tags, :id]
Add typespec
```elixir
@type t :: %__MODULE__{
title: String.t()
# ...
}
```

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo/article.ex
> +defmodule Kotkowo.Article do
Add typespec

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      <button :if={@selected_page != 1} phx-click="select_page" class="p-4" value={@selected_page - 1}>
Don't include `phx-` tags in regular components.
Either move this to a LiveComponent or pass the `phx-` attributes from the parent.

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      |> assign(:next_page, assigns.selected_page + 1)
Don't do any logic here.
Either assign this from the parent or move this to a LiveComponent.
Handle cases where page might be <= 0 and >= max_page

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +        <text :if={@selected_page > 2} class="w-14 h-14">...</text>
No such thing as a `text` tag in HTML5 spec:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      <button :if={@selected_page != 1} phx-click="select_page" class="p-4" value={@selected_page - 1}>
You're assuming that 1 is the starting index.
Such assumptions should be put in a module attribute:

```elixir
defmodule KotkowoWeb.Components.PaginationBar do
  @moduledoc false

  use Phoenix.Component

  @first_page 1
```

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      <img :if={@selected_page == 1} class="p-4" src="/images/arrow_left.svg" />
Don't use paths without using the `~p` sigil

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +        <img class="-scale-100" src="/images/arrow_right.svg" />
Don't use paths without using the ~p sigil

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      <button :if={@selected_page != 1} phx-click="select_page" class="p-4" value={@selected_page - 1}>
and then refer to them instead of using magic numbers
https://en.wikipedia.org/wiki/Magic_number_(programming)

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      |> assign(:next_page, assigns.selected_page + 1)
Phoenix components are for reusing markup not handling logic.

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      <button :if={@selected_page != 1} phx-click="select_page" class="p-4" value={@selected_page - 1}>
This will prevent user's from using this without knowing that they need to implement the event handler.

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +        <button :if={@selected_page > 2} class="w-14 h-14" phx-click="select_page" value={1}>
Don't include `phx-` tags in regular components.
Either move this to a LiveComponent or pass the `phx-` attributes from the parent.

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +          :if={@selected_page != 1}
magic number

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +        <text :if={@selected_page > 2} class="w-14 h-14">...</text>
magic number here

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      <img :if={@selected_page == 1} class="p-4" src="/images/arrow_left.svg" />
magic number here

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +          phx-click="select_page"
dont use `phx-` in Phoenix components

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +          phx-click="select_page"
dont use `phx-` in Phoenix components

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +        <text :if={@selected_page < @last_page - 1} class="w-14 h-14">...</text>
No such thing as a HTML5 `text` element

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +      <img :if={@selected_page == @last_page} class="-scale-100 p-4" src="/images/arrow_left.svg" />
use `~p`. don't use `scale-` on SVGs, setting width and height preferred.

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +        phx-click="select_page"
Don't use `phx-`

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/components/pagination_bar.ex
> +        <img src="/images/arrow_right.svg" />
Use `~p`

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/adopted.ex
Delete this empty file

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/all_news.html.heex
> +          <option value="90" selected={@limit == 90}>90</option>
Move this to a loop, fetch available options from a `defp`

```elixir
defp items_per_page(), do: [30, 60, 90]
```

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/latest_news.ex
> +    {:ok, news} = StrapiClient.list_announcements(4, 3)
This results in 3 hits to Strapi. All you need is 1.

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/latest_news.ex
> +    {:ok, article} = StrapiClient.get_article(Integer.to_string(hd(header_news).id))
What is this fetching? It looks like it's refetching. If it's fetching a related article rename it to `get_article_for_announcement(announcement_id)`

I have no idea how this passed the formatter check. 
Fix this.

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/news_article.ex
> +    with {:ok, %Article{} = article} <- StrapiClient.get_article(article_id) do
What happens when this fails?

2023-09-23 11:46 UTC, ravensiris commented on lib/kotkowo_web/router.ex
> +      live "/z-ostatniej-chwili/:article_id", NewsLive.NewsArticle
Put them in a scope

2023-09-23 11:46 UTC, ravensiris commented on native/strapiclient/src/query/get_article.graphql
Format this.

2023-09-23 11:46 UTC, ravensiris commented on native/strapiclient/src/query/list_announcement.graphql
> +query ListAnnouncementQuery($limit: Int, $offset: Int){
Format this

2023-09-23 11:46 UTC, ravensiris commented on native/strapiclient/src/query/list_announcement.rs
> +        //let announcements: Result<Vec<Announcement>> = value.data.into_iter()
Remove this comment

2023-09-23 11:46 UTC, ravensiris commented on native/strapiclient/src/query/list_cat.graphql
> +query CatListQuery{
Format this

2023-10-08 15:34 UTC, RustySnek commented
closed in favor of #40

2023-10-08 15:34 UTC, closed without merging