🐛  Fix/news pages
kotkowo/kotkowo pull request #42
Opened 2023-10-26 19:49 UTC by RustySnek

2023-10-26 23:11 UTC, ravensiris requested changes

2023-10-26 23:11 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/all_news.ex
> +
Quick maths:

```elixir
max(1, max_page)
```

2023-10-26 23:11 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/latest_news.ex
> +
Terrible. You don't check length like in procedural languages in Elixir.

```elixir
{first_news, news} = List.pop_at(news, 0)
```

2023-10-26 23:11 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/latest_news.ex
>      popular_news = Enum.take(tail, 2)
Use
```elixir
{popular_news, news} = Enum.split(news, 2)
```

2023-10-26 23:11 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/latest_news.ex
>        |> Enum.take(4)
Now just `Enum.take(news, 4)`

2023-10-26 23:11 UTC, ravensiris commented on lib/kotkowo_web/live/news_live/latest_news.ex
> +      end
Here's a cleaner solution
```elixir
defp get_article(%News{} = news) do
   case StrapiClient.get_article_for_announcement(news.id) do
      {:ok, %Article{} = article} -> article
      _ -> nil
   end
end

# ...
article = get_article(header)
socket = assign(socket, :article, article)
```

2023-10-27 09:25 UTC, RustySnek reviewed
Done

2023-10-27 09:27 UTC, ravensiris approved these changes

2023-10-27 09:36 UTC, merged