About us
kotkowo/kotkowo pull request #88
Opened 2024-10-04 21:30 UTC by RustySnek

2024-10-14 20:39 UTC, ravensiris requested changes

2024-10-14 20:39 UTC, ravensiris commented on lib/kotkowo_web/live/about_us_live/fundation_history.ex
> +        {:error, msg} -> Logger.error(msg)
return a valid socket here(with a error msg preferably)

2024-10-15 07:03 UTC, RustySnek commented on lib/kotkowo_web/live/about_us_live/fundation_history.ex
> +        {:error, msg} -> Logger.error(msg)
💀

2024-10-15 07:23 UTC, ravensiris approved these changes
Fix CI errors before merge

2024-10-15 16:15 UTC, merged